[phases.setup]
nixPkgs = ['python311', "pip",'libGL', 'libGLU', 'mesa']

[phases.install]
cmds = ['pip install --upgrade pip', 'pip install -r requirements.txt']

[start]
cmd = "uvicorn recognize_faces:app --host 0.0.0.0 --port $PORT"
